export enum EOriginRoutes {
  AUTH_GUARD = 'authGuard',
  ACCOUNT = 'account',
  AUTH = 'auth',
  FUNNELS = 'funnels',
  FUNNELS_PUBLIC = 'publicFunnels',
  KEYS = 'keys',
  MEMBERS = 'members',
  ORGANIZATIONS = 'organizations',
  PERMISSIONS = 'permissions',
  PLANS = 'plans',
  ROLES = 'roles',
  SERVICES = 'services',
  STATISTICS = 'statistics',
  TENANTS = 'tenants',
  TRACKERS = 'trackers',
  USERS = 'users',
}
